# Generated by Django 3.0.7 on 2020-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.CharField(max_length=100),
        ),
    ]
